### PR TITLE
Adding main activity as default activity to start

### PR DESCRIPTION
**Pull request by luispereira**
In order to better use external tools to install and execute your app faster e.g. [dryrun](https://github.com/cesarferreira/dryrun)
Adding MainActivity as default activity on manifest

### CODE REVIEW

**Comment by luispereira** [comment]
Additionally, I think I found a mistake on the package field in manifest as
tk.elevek.proxysetter instead of tk.elevenk.proxysetter or vice versa

Let me know if you want me to change it too.

Just be aware that with these changes the actual code as it is to execute this is 
```
adb shell am start -n tk.elevek.proxysetter/tk.elevenk.proxysetter.MainActivity 
```

and not:
```
adb shell am start -n tk.elevenk.proxysetter/tk.elevenk.proxysetter.MainActivity
```
or 
```
adb shell am start -n tk.elevenk.proxysetter/.MainActivity
```

**Comment by manadream** [comment]
Ah, thanks, there is a typo. It should be `tk.elevenk.proxysetter`.
These changes look fine, although this app is not meant to be launched by the user on the phone itself, it's for automation purposes to be launched from adb.

**Comment by luispereira** [comment]
Ok, up to you rejecting it or not ;)

**Comment by manadream** [comment]
Looks good, thanks!

**Pull request merged**
